name: metacoder
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.3.11=h06a4308_0
  - expat=2.6.2=h6a678d5_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.14=h5eee18b_0
  - pip=24.0=py312h06a4308_0
  - python=3.12.2=h996f2a0_0
  - readline=8.2=h5eee18b_0
  - setuptools=69.5.1=py312h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.43.0=py312h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - alembic==1.13.1
      - blinker==1.8.2
      - click==8.1.7
      - dnspython==2.6.1
      - dominate==2.9.1
      - email-validator==2.2.0
      - et-xmlfile==2.0.0
      - flask==3.0.3
      - flask-bootstrap==3.3.7.1
      - flask-ckeditor==1.0.0
      - flask-login==0.6.3
      - flask-migrate==4.0.7
      - flask-sqlalchemy==3.1.1
      - flask-uploads==0.2.1
      - flask-wtf==1.2.1
      - greenlet==3.0.3
      - idna==3.7
      - itsdangerous==2.2.0
      - jinja-markdown==1.210911
      - jinja2==3.1.4
      - mako==1.3.5
      - markdown==3.6
      - markupsafe==2.1.5
      - numpy==2.0.0
      - openpyxl==3.1.5
      - pandas==2.2.2
      - pygments==2.18.0
      - pymdown-extensions==10.8.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - six==1.16.0
      - sqlalchemy==2.0.31
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - visitor==0.1.3
      - werkzeug==3.0.3
      - wtforms==3.1.2
prefix: /home/bartosz/.conda/envs/metacoder
